# Generated by Django 6.0.6 on 2026-08-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_chapter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
